[Feature] - Create useMousePosition hook
novajslabs/nova.js pull request #135
Opened 2024-11-27 13:17 UTC by Lucas-Tisera

## Description
Added `useMousePosition` hook to track mouse coordinates in real-time. This hook provides a simple way to access the current mouse position (x, y) coordinates anywhere in the application.

### Related Issue
Implements the mouse tracking hook requested in [#88](https://github.com/novajslabs/nova.js/issues/88)

### Features
- Real-time mouse position tracking
- Automatic cleanup of event listeners
- Zero dependencies
- Lightweight implementation

### Usage Example

```javascript
const { x , y } = useMousePosition();

console.log(Mouse is at: ${ x }, ${ y });
```

### Why
- Simplifies mouse position tracking across components
- Useful for interactive UI elements, animations, and custom cursors
- Follows React best practices with proper cleanup

### Technical Details
- Uses `window.addEventListener` for mouse tracking
- Implements proper cleanup in useEffect
- Returns coordinates as `{ x, y }` object

2024-12-03 15:12 UTC, dlcastillop requested changes
Great job, Lucas! Just check out the comments I made in the code. Thank you.

2024-12-04 21:10 UTC, Lucas-Tisera commented on src/hooks/js/useMousePosition.js
> +function useMousePosition() {
mb, forgotten

2024-12-09 11:31 UTC, dlcastillop requested changes

2024-12-09 11:31 UTC, dlcastillop commented on src/hooks/js/useMousePosition.js
> +  useEffect(() => {
Look at this implementation. It works for me.

```ts
import { useSyncExternalStore } from 'react';

interface MousePosition {
  x: number;
  y: number;
}

let mousePosition: MousePosition = { x: 0, y: 0 };

export const useMousePosition = (): MousePosition => {
  const subscribe = (callback: () => void) => {
    const handleMouseMove = (event: MouseEvent) => {
      mousePosition = {
        x: event.clientX,
        y: event.clientY
      };
      callback();
    };

    window.addEventListener('mousemove', handleMouseMove);
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
    };
  };

  const getSnapshot = (): MousePosition => mousePosition;

  const getServerSnapshot = (): MousePosition => ({ x: 0, y: 0 });

  return useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);
};
```

2024-12-09 11:31 UTC, dlcastillop commented on src/App.tsx
Don´t modify this file.

2024-12-10 15:55 UTC, Lucas-Tisera commented on src/hooks/js/useMousePosition.js
> +  useEffect(() => {
It works 😁, thanks for the suggestion!

2024-12-24 11:06 UTC, dlcastillop approved these changes
Amazing job Lucas. Thank you!

2024-12-24 11:08 UTC, merged