Feature: create search params hooks
novajslabs/nova.js pull request #75
Opened 2024-05-21 21:10 UTC by alnavarrop99

**Description**:
Hook for reading the search parameters of the route as an argument or of the current route.

**Uses Cases**:
- ```useSearchParams()```: current url search params.
- ```useSearchParams("https://example.com?foo=1&bar=2&foo=2")```: foo: 1, bar: 2.
- ```useSearchParams("https://example.com?foo=1&bar=2&foo=2", { unique: false })```: foo: [1,2], bar: 2.

_Examples_: 
```tsx
import { useSearchParams } from "./hooks/ts/useSearchParams";

const App = () => {
  const params = useSearchParams("https://example.com?foo=1&bar=2&foo=2", { unique: true })
  return <div>
    <p>Typescript test:</p>
    { Object.entries(params)?.map( ([key, value]) => (
      <p key={key}>
        <span>{key}</span>: <span>{value}</span>
      </p>
    ) ) }
  </div>
};

export default App;
```

2024-05-21 21:14 UTC, alnavarrop99 commented
Do you also think it's necessary to include search parameter modification methods like `has`, `set`, `append`, `delete` that interact directly with the route? I'm not sure if it's a good idea since in most cases the project's router handles this, and I'm not completely sure if there could be incompatibilities between the hook and the router. [Moxilla](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/append)

2024-05-22 09:42 UTC, dlcastillop requested changes
Update your branch with the latest changes in the repo. Now, you only must provide the hook in TypeScript (like you sugested 🙌) and all hooks are in the `hooks` directory.

2024-05-22 09:44 UTC, dlcastillop commented
> Do you also think it's necessary to include search parameter modification methods like `has`, `set`, `append`, `delete` that interact directly with the route? I'm not sure if it's a good idea since in most cases the project's router handles this, and I'm not completely sure if there could be incompatibilities between the hook and the router. [Moxilla](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/append)

I do not think we must include it because like you said normally the project's router handles this.

2024-05-22 10:02 UTC, dlcastillop requested changes

2024-05-22 10:02 UTC, dlcastillop commented on src/hooks/ts/useSearchParams.ts
> +  const _urlSearch = new URL(url)
When I use the hook without specify an url this error ocurrs:

useSearchParams.ts:5 Uncaught TypeError: Failed to construct 'URL': Invalid URL at useSearchParams (useSearchParams.ts:5:22)

```ts
import { useSearchParams } from "./hooks/ts/useSearchParams";

const AppTs = () => {
  const params = useSearchParams();
  return (
    <div>
      <p>Typescript test:</p>
      {Object.entries(params)?.map(([key, value]) => (
        <p key={key}>
          <span>{key}</span>: <span>{value}</span>
        </p>
      ))}
    </div>
  );
};

export default AppTs;
```

2024-05-22 15:55 UTC, alnavarrop99 commented
Ready, I have resolved the conflicts and corrected the current path error.

2024-05-24 12:03 UTC, dlcastillop requested changes

2024-05-24 12:03 UTC, dlcastillop commented on src/hooks/useSearchParams.ts
> +type TUseSearchParams = ( url?: string, opt?: { unique: boolean } ) => Record<string, any>
I am also getting a lot of problems with the types

<img width="960" alt="image" src="https://github.com/novajslabs/nova.js/assets/63487673/6a693693-4aa7-48e1-a183-9d3f24774f07">

Does not your linter show it to you?

2024-05-26 11:05 UTC, dlcastillop commented
Great work @alnavarrop99! 🙌

2024-05-26 11:06 UTC, merged